[window]
opacity = 0.95
startup_mode = "Maximized" 
decorations = "None"

[font]
normal.family = "DroidSansM Nerd Font Mono"
bold.family = "DroidSansM Nerd Font Mono"
italic.family = "DroidSansM Nerd Font Mono"
bold_italic.family = "DroidSansM Nerd Font Mono"
size = 12

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[colors.primary]
background = '#171421'
foreground = '#ffffff'

[colors.normal]
black      = '#171421'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#d0cfcc'

[colors.bright]
black      = '#5e5c64'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#ffffff'
